appcelerator/appc-platform-sdk

lib/app.js

Adds a platform API to enable performance service and returns the id.

Adding API for crittercism

---

.gitignore
.travis.yml
Gruntfile.js
package.json

Implemented 
- appc-coverage
- grunt-kahvesi

Implemented appc-coverage & grunt-kahvesi

---

lib/app.js

- Implement _App.update()_ for use in _appc-cli-titanium/plugins/new.js_
NOTE : This is a dependency of [appc-cli-titanium/pull/48](https://github.com/appcelerator/appc-cli-titanium/pull/48)
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-505)

[CLI-505] Implement App.update()

---

lib/cloud.js

https://jira.appcelerator.org/browse/CLI-515

[CLI-515] Unable to recreate ACS keys for mobile app

---

lib/auth.js

- Fixed handling of the argument ```object``` which has a ```typeof``` string.
[Jira Ticket](https://jira.appcelerator.org/browse/CLI-620)

[CLI-620] Fixed handling of the arguments

---

lib/auth.js
package.json
test/appc_platform_sdk_tests.js

The login method is modified to accept params such as username, password, mid and from. It do supports backward compatibility as well in order to support other node modules accidentally using this new major version bumped module.

REG-76 Send login analytics data to PEM

---

lib/auth.js
package.json

https://jira.appcelerator.org/browse/REG-76

[REG-76] Send login analytics data to PEM fix

---

lib/auth.js
lib/index.js

https://jira.appcelerator.org/browse/CLI-989
Depends on appcelerator/appc-install#52

[CLI-989] added "strictSSL" & "cafile" to request

---

lib/auth.js
lib/index.js
package.json

JIRA: https://jira.appcelerator.org/browse/CLI-989

[CLI-989] CLI not responding on self signed certificate

---

lib/auth.js
test/helper.js

JIRA: https://jira.appcelerator.org/browse/CLI-989

[CLI-989] fix tests and missing require

---

lib/index.js
package.json

https://jira.appcelerator.org/browse/API-1298
When passing an environment variable `productioneu` appc-platform-sdk will load the the urls for the eu region.

[API-1298] EU region

---

lib/auth.js
test/appc_platform_sdk_tests.js

This adds the entitlement object to the session object that is returned from createSessionFromID

added entitlements to createSessionFromID

---

lib/auth.js
package.json
test/appc_platform_sdk_tests.js

https://jira.appcelerator.org/browse/CLI-1057
As part of adding entitlements to appc-platform-sdk call i mistakenly removed id and name fields from this PR: https://github.com/appcelerator/appc-platform-sdk/pull/43
This PR will add the necessary field that CLI needs.

[CLI-1057] add entitlements id & name

---

lib/auth.js
package.json
test/appc_platform_sdk_tests.js

https://jira.appcelerator.org/browse/CLI-1057
As part of adding entitlements to appc-platform-sdk call i mistakenly removed id and name fields from this PR: #43
This PR will add the necessary field that CLI needs.

[CLI-1057] entitlements id & name

---

lib/index.js
package.json

https://jira.appcelerator.org/browse/API-1373
Adds support for platform-axway environment.

[API-1373] add platform-axway

---

lib/app.js
test/app.js

Reverts test changes and callback args passed out of Appc.App.create to return app obj rather than response.

Wrap saveFromTiApp callback to pass back app obj

---

lib/index.js
package.json
test/appc_platform_sdk_tests.js

Backporting changes needed for onprem:
https://jira.appcelerator.org/browse/APPTS-9277

[APPTS-9277] Inherit Env props from process.env vars

---

lib/index.js
package.json

https://jira.appcelerator.org/browse/CLI-1250

[CLI-1250] Add proxy pac file support

---

package.json
test/app.js
test/auth.js
test/middleware.js

This PR updates the test cycles to get it passing (for now). Had to skip a couple of things which need further debug, but appears to be an issue with state on the platform that needs resolving (and is out of my control, as I'm knew to this codebase).

[APPTS-9536] Updated test cycles to ensure passing build

---

lib/analytics.js
package-lock.json
package.json
test/analytics.js
test/cloud.js
test/middleware.js

Adds missing package-lock.json updates and bumps dev deps to mitigate flagged vulns. Also, adds some linting touch-ups.

Package updates

---

.eslintrc
lib/cloud.js
lib/index.js
package-lock.json
package.json
test/conf/loader.js
test/middleware.js

Fix vuln in https-proxy-agent by updating to latest pac-proxy-agent package

3.0.3 - Update dependencies
